name: React Native - RN CLI

on:
  push:
    branches: [main]
    paths: ['examples/native-cli/**']
  pull_request:
    branches: ['**']
    paths: ['examples/native-cli/**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'main')}}

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install Example
        run: yarn --cwd examples/native-cli install

      - name: Validate TypeScript
        run: yarn --cwd examples/native-cli typecheck

      - name: Validate ESLint
        run: yarn --cwd examples/native-cli lint

      - name: Run tests
        run: yarn --cwd examples/native-cli test

      - name: Run perf tests
        run: cd examples/native-cli && ./reassure-tests.sh

      - name: Run Danger.js
        run: yarn --cwd examples/native-cli danger ci --id native
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
