name: Web - Vite

on:
  push:
    branches: [main]
    paths: ['examples/web-vite/**']
  pull_request:
    branches: ['**']
    paths: ['examples/web-vite/**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'main')}}

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: Install Example
        run: yarn --cwd examples/web-vite install

      - name: Validate TypeScript
        run: yarn --cwd examples/web-vite typecheck

      - name: Validate ESLint
        run: yarn --cwd examples/web-vite lint

      - name: Run tests
        run: yarn --cwd examples/web-vite test

      - name: Run perf tests
        run: cd examples/web-vite && ./reassure-tests.sh

      - name: Run Danger.js
        run: yarn --cwd examples/web-vite danger ci --id web-vite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
