name: Test Example Web Vite

on: [workflow_dispatch]

jobs:
  web-vite:
    name: Run perf test in Web Vite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'

      - name: Install and build
        run: yarn --cwd examples/web-vite install

      - name: Validate TypeScript
        run: yarn --cwd examples/web-vite typecheck

      - name: Validate ESLint
        run: yarn --cwd examples/web-vite lint

      - name: Run tests
        run: yarn --cwd examples/web-vite test

      - name: Run perf tests
        run: yarn --cwd examples/web-vite ./reassure-tests.sh

      - name: Run Danger.js
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
