name: Test Example Web Nextjs

on: [workflow_dispatch]

jobs:
  web-nextjs:
    name: Run perf test in Web Nextjs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'

      - name: Install and build
        run: yarn --cwd examples/web-nextjs install

      - name: Validate TypeScript
        run: yarn --cwd examples/web-nextjs typecheck

      - name: Validate ESLint
        run: yarn --cwd examples/web-nextjs lint

      - name: Run tests
        run: yarn --cwd examples/web-nextjs test

      - name: Run perf tests
        run: yarn --cwd examples/web-nextjs ./reassure-tests.sh

      - name: Run Danger.js
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
