name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  test-native:
    name: Test React Native CLI Example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install Root
        run: yarn install

      - name: Install Example
        run: yarn --cwd examples/native install

      - name: Validate TypeScript
        run: yarn --cwd examples/native typecheck

      - name: Validate ESLint
        run: yarn --cwd examples/native lint

      - name: Run tests
        run: yarn --cwd examples/native test

      - name: Run perf tests
        run: cd examples/native && ./reassure-tests.sh

      - name: Run Danger.js
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
